name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Notebook
      run: |
        pip install nbconvert
        jupyter nbconvert --to notebook --execute --inplace notebooks/Trash_Type_Classifications.ipynb
