name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Jupyter and nbconvert
      run: |
        pip install jupyter nbconvert

    - name: Install and Setup Kernel
      run: |
        pip install ipykernel
        python -m ipykernel install --user --name=trash_class

    - name: Run Notebook
      run: |
        jupyter nbconvert --to notebook --execute --inplace notebooks/Trash_Type_Classifications.ipynb
